const LETTERS = [
  { character: 'E', frequency: 12.7, cryto: 'D' },
  { character: 'T', frequency:  9.1, cryto: 'G' },
  { character: 'A', frequency:  8.2, cryto: 'Q' },
  { character: 'O', frequency:  7.5, cryto: 'T' },
  { character: 'I', frequency:  7.0, cryto: 'C' },
  { character: 'N', frequency:  6.7, cryto: '_' },
  { character: 'S', frequency:  6.3, cryto: '_' },
  { character: 'H', frequency:  6.1, cryto: '_' },
  { character: 'R', frequency:  6.0, cryto: '_' },
  { character: 'D', frequency:  4.3, cryto: '_' },
  { character: 'L', frequency:  4.0, cryto: '_' },
  { character: 'C', frequency:  2.8, cryto: '_' },
  { character: 'U', frequency:  2.8, cryto: '_' },
  { character: 'M', frequency:  2.4, cryto: '_' },
  { character: 'W', frequency:  2.4, cryto: '_' },
  { character: 'F', frequency:  2.2, cryto: '_' },
  { character: 'G', frequency:  2.0, cryto: '_' },
  { character: 'Y', frequency:  2.0, cryto: '_' },
  { character: 'P', frequency:  1.9, cryto: '_' },
  { character: 'B', frequency:  1.5, cryto: '_' },
  { character: 'V', frequency:  1.0, cryto: '_' },
  { character: 'K', frequency:  0.8, cryto: '_' },
  { character: 'J', frequency:  0.2, cryto: '_' },
  { character: 'Q', frequency:  0.1, cryto: '_' },
  { character: 'X', frequency:  0.1, cryto: '_' },
  { character: 'Z', frequency:  0.1, cryto: '_' },
];
